GET http://localhost:4003/orders

###
POST http://localhost:4003/orders
Content-Type: application/json

{
    "name":"Order 10",
    "sender":"amos@gmail.com",
    "sendername": "'Amos'",
    "receiver":"amwongelah@gmail.com",
    "receivername": "Mwongela",
    "destination": "Keru",
    "destination": "Keru",
    "weight": 112,
    "price": 1
}
###

GET http://localhost:4003/orders


###

GET http://localhost:4003/orders/354eae15-6c10-421b-9999-51e0b3d45c84


####
PUT http://localhost:4003/orders/update/e26c1938-3859-43e8-b0e0-ab072ec88f5d
Content-Type: application/json

{
    "name":"Order 10",
    "sender":"amos@gmail.com",
    "sendername": "Amos",
    "receiver":"mwongela@gmail.com",
    "receivername": "Mwongela",
    "destination": "Keru",
    "destination": "Keru",
    "weight": 112,
    "price": 1,
    "status":"Delivered"
    
}

###
DELETE http://localhost:4003/orders/570a35ad-8f3b-4c76-9cff-e7e783c66540