GET http://localhost:4003/orders

###
POST http://localhost:4003/orders
Content-Type: application/json

{
    "name":"Order 1",
    "sender":"Amos",
    "receiver":"Mwongela",
    "destination": "Keru",
    "status":"Shipping",
    "isDeleted": false
}

###

GET http://localhost:4003/orders


###

GET http://localhost:4003/orders/354eae15-6c10-421b-9999-51e0b3d45c84


####
PUT http://localhost:4003/orders/update/354eae15-6c10-421b-9999-51e0b3d45c84
Content-Type: application/json

{
    "name":"Test Order",
    "sender":"Amos",
    "receiver":"Amos",
    "destination": "Keru",
    "status":"Delivered"
}

###
DELETE http://localhost:4003/orders/68d305da-d238-4606-884b-2713ab27032f