### NEW ORDER
POST http://localhost:4003/orders
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmMjY3MjYzLTkzNWEtNGRkMC05MGEzLWU0ZTljNWM2ODZmNyIsIm5hbWUiOiJBbW9zIiwiZW1haWwiOiJhbW9zbXdvbmdlbGFoQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlzV2VsY29tZWQiOnRydWUsImlhdCI6MTY2MzkxMzQ2NywiZXhwIjoxNjYzOTE3MDY3fQ._F0PaXO3nYLWMUE_6jhjxmC1e72ddlsTACOnTRufG6w

{
    "name":"New Order2",
    "sender":"amos@gmail.com",
    "sendername": "Amos",
    "receiver":"amos@gmail.com",
    "receivername": "Mwongela",
    "destination": "Keru",
    "destination": "Keru",
    "lat": 34,
    "lng": 34,
    "weight": "112",
    "price": "11219"
}

### UPDATE SPECIFIC ORDER(Status or Details)
PUT http://localhost:4003/orders/update/5764d336-77e1-481e-aed5-0af1dc2e942a
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmMjY3MjYzLTkzNWEtNGRkMC05MGEzLWU0ZTljNWM2ODZmNyIsIm5hbWUiOiJBbW9zIiwiZW1haWwiOiJhbW9zbXdvbmdlbGFoQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlzV2VsY29tZWQiOnRydWUsImlhdCI6MTY2MzU4NjM2MSwiZXhwIjoxNjYzNTg5OTYxfQ.XT0CqizJmq4yjTsHxpFw4Y7NJelChp0P--48_SGxDl8

{
    "name":"Updated Order",
    "sender":"amos@gmail.com",
    "sendername": "Amos",
    "receiver":"amosmwongelah@gmail.com",
    "receivername": "Mwongela",
    "destination": "Keru",
    "destination": "Keru",
    "weight": 112,
    "price": 1,
    "status":"Delivered"
    
}

### GET ALL ORDERS
GET http://localhost:4003/orders
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmMjY3MjYzLTkzNWEtNGRkMC05MGEzLWU0ZTljNWM2ODZmNyIsIm5hbWUiOiJBbW9zIiwiZW1haWwiOiJhbW9zbXdvbmdlbGFoQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlzV2VsY29tZWQiOnRydWUsImlhdCI6MTY2MzU4MzkyOSwiZXhwIjoxNjYzNTg3NTI5fQ.j4_fwEDiM66hEsixaqF5VnmugoWJEjYgwAyMJPTxsAE


### GET SPECIFIC ORDER
GET http://localhost:4003/orders/5764d336-77e1-481e-aed5-0af1dc2e942a
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmMjY3MjYzLTkzNWEtNGRkMC05MGEzLWU0ZTljNWM2ODZmNyIsIm5hbWUiOiJBbW9zIiwiZW1haWwiOiJhbW9zbXdvbmdlbGFoQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlzV2VsY29tZWQiOnRydWUsImlhdCI6MTY2MzU4MzkyOSwiZXhwIjoxNjYzNTg3NTI5fQ.j4_fwEDiM66hEsixaqF5VnmugoWJEjYgwAyMJPTxsAE



### SOFT DELETE
DELETE http://localhost:4003/orders/5764d336-77e1-481e-aed5-0af1dc2e942a
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmMjY3MjYzLTkzNWEtNGRkMC05MGEzLWU0ZTljNWM2ODZmNyIsIm5hbWUiOiJBbW9zIiwiZW1haWwiOiJhbW9zbXdvbmdlbGFoQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlzV2VsY29tZWQiOnRydWUsImlhdCI6MTY2MzU4MzkyOSwiZXhwIjoxNjYzNTg3NTI5fQ.j4_fwEDiM66hEsixaqF5VnmugoWJEjYgwAyMJPTxsAE
