###NEW USER(Admin)
POST http://localhost:4003/user/signup
Content-Type: application/json

{
    "name": "Amos",
    "email":"amosmwongelah@gmail.com",
    "password":"1to34567"
}
###ANOTHER USER
POST http://localhost:4003/user/signup
Content-Type: application/json

{
    "name": "User 2",
    "email":"cmplyamos113@gmail.com",
    "password":"1to34567"
}

###LOGIN Amos(Admin)
POST http://localhost:4003/user/login
Content-Type: application/json

{
    "email":"amosmwongelah@gmail.com",
    "password":"1to34567"
}
###LOGIN User 2(User)
POST http://localhost:4003/user/login
Content-Type: application/json

{
    "email":"cmplyamos113@gmail.com",
    "password":"1to345678"
}